# Generated by Django 4.2.1 on 2023-05-31 10:58

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=blog.models.NameField(max_length=200),
        ),
    ]
